version: '3.7'
services:
  frontend:
    container_name: frontend
    build: 
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    volumes:
      - './app:/app'
      - '/app/node_modules'
    # env_file: 
    #   - './app/.env'
    ports:
      - "3000:3000"
    command: npm start
    environment:
      - REACT_APP_NAME=frontend_DEV
      - CHOKIDAR_USEPOLLING=true
